baseURL = 'https://aiflowkit.xyz/'
title = 'AI Flow Kit | Expert Reviews of AI Productivity Tools'
languageCode = 'en-us'
defaultContentLanguage = 'en'
theme = "blowfish"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
enableEmoji = true
metaDataFormat = "json-ld"

[imaging]
  quality = 80
  resampleFilter = "lanczos"

[security]
  [security.csp]
    scriptSrc = ["'self'", "https://pagead2.googlesyndication.com", "https://www.google.com", "https://www.gstatic.com", "https://www.recaptcha.net", "https://www.gstatic.com/recaptcha/"]
    styleSrc = ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"]
    fontSrc = ["'self'", "https://fonts.gstatic.com"]
    imgSrc = ["'self'", "data:", "https:", "https://*.google.com", "https://*.gstatic.com"]

# ===== SITE PARAMS =====
[params]
  description = "Boost your productivity with expert reviews and tutorials on the latest AI tools. We test so you don't have to."
  keywords = ["AI tools", "productivity", "software reviews", "automation", "machine learning", "SaaS", "developer tools"]
  dateFormat = "January 2, 2006"
  repoURL = "https://github.com/WIZOO1/aiflow-blog"
  color = "blue"
  fontSize = "base"
  images = ["/images/og-image.png"]

  [params.social]
    twitter = "aiflowkit"
    github = "WIZOO1"

  [params.ads]
    enable = false
    google_adsense = "ca-pub-your-publisher-id"

  [params.newsletter]
    enable = true
    title = "Join the AI Productivity Insider"
    description = "Get weekly reviews of new AI tools and productivity hacks."

[author]
  name = "AI Flow Kit Team"
  # You can add more author fields later:
  # email = "your@email.com"
  # link = "https://aiflowkit.xyz/about"

# ===== MENU STRUCTURE =====
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "reviews"
  name = "Tool Reviews"
  url = "/categories/reviews/"
  weight = 20

# ... (keep the rest of your menu configuration exactly as it was) ...
[author]  name = "AI Flow Kit Team"
  # You can add more author fields later:
  # email = "your@email.com"
  # link = "https://aiflowkit.xyz/about"
  
  color = "blue"
  fontSize = "base"
  
  images = ["/images/og-image.png"]
  

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "reviews"
  name = "Tool Reviews"
  url = "/categories/reviews/"
  weight = 20

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials"
  url = "/categories/tutorials/"
  weight = 30

[[menu.main]]
  identifier = "comparisons"
  name = "Comparisons"
  url = "/categories/comparisons/"
  weight = 40

[[menu.main]]
  identifier = "news"
  name = "AI News"
  url = "/categories/news/"
  weight = 50

[[menu.main]]
  identifier = "resources"
  name = "Resources"
  url = "/resources/"
  weight = 60
  hasChildren = true

[[menu.main]]
  parent = "resources"
  name = "Free Courses"
  url = "/resources/courses/"
  weight = 10

[[menu.main]]
  parent = "resources"
  name = "Templates"
  url = "/resources/templates/"
  weight = 20

[[menu.footer]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 10

[[menu.footer]]
  name = "Terms of Service"
  url = "/terms-of-service/"
  weight = 20

[[menu.footer]]
  name = "Disclaimer"
  url = "/disclaimer/"
  weight = 30

[[menu.footer]]
  name = "Contact"
  url = "/contact/"
  weight = 40

[[menu.footer]]
  name = "About Us"
  url = "/about/"
  weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
